apiVersion: v1
kind: ConfigMap
metadata:
  name: region-config
  namespace: default
data:
  aws.default.region: eu-central-1
  game.server.queue.name:  gameserver-q-GSQueue-1LIJUQ1SL9MI2
  game.server.queue.url: https://eu-central-1.queue.amazonaws.com/356566070122/gameserver-q-GSQueue-1LIJUQ1SL9MI2
  spot.int.queue.url: https://eu-central-1.queue.amazonaws.com/356566070122/spotint-q-SpotQueue-4I1000FHS3V

